tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "railwaycat/emacsmacport"

brew "openssl"
brew "asdf"
brew "aspell"
brew "autojump"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "bash-git-prompt"
brew "cask"
brew "fzf"
brew "git"
brew "gnupg"
brew "httpie"
brew "ispell"
brew "jq"
brew "packer"
brew "ruby-build"
brew "rbenv"
brew "stow"
brew "tfenv"
brew "tldr"
brew "tree"
brew "yarn"
brew "heroku/brew/heroku"

cask "alfred"
cask "bettertouchtool"
cask "chromedriver"
cask "docker"
cask "emacs-mac-spacemacs-icon"
cask "firefox"
cask "font-fira-code"
cask "font-input"
cask "font-source-code-pro"
cask "iterm2"
cask "karabiner-elements"
cask "ngrok"
cask "psequel"
cask "sequel-pro"
cask "spectacle"
cask "spotify"
cask "vagrant"


mas "taurine", id: 960276676
mas "Slack", id: 803453959
mas "Xcode", id: 497799835
